---
name: Bump

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  check:
    name: check whether version is bumped
    runs-on: ubuntu-latest
    outputs:
      new: ${{ steps.parse.outputs.new }}
    steps:
      
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Parse package.json for version update
        id: parse
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          hub release | grep $(jq -r '.version' package.json) \
          && echo "new=false" >> "$GITHUB_OUTPUT" \
          || echo "new=true"  >> "$GITHUB_OUTPUT"
  
  release:
    needs: check
    if: needs.check.outputs.new == 'true'
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
