name: CI

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - name: Lint
        run: deno task lint
  
  type-check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - name: Check
        run: deno task check
  
  test-deno:
    name: test on deno
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - name: Build
        run: deno task build
      
      - name: Test
        run: deno task test:deno
  
  test-node:
    name: test on node
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install TypeScript
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test:node
