name: CI

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - run: deno task lint
  
  type-check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - run: deno task check
  
  test-deno:
    name: test on deno
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - run: deno task build
      - run: deno task test:deno
  
  test-node:
    name: test on node
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - run: npm install && npm run build
      - run: npm run test:node
  
  artifacts:
    name: ensure build artifacts are current
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      
      - run: deno task build
      - run: git add . && git diff-index --quiet HEAD
      - if: failure()
        run: git diff-index HEAD
