name: Publish to NPM

on:
  push:
    branches:
      publish-to-npm
  release:
    types: [created]

jobs:
  build-test-publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35
      - name: Build
        run: npm run build
      - name: Test on Node
        run: npm run test:node
      - name: Test on Deno
        run: npm run test:deno
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
