name: Release

on:
  workflow_call:

jobs:
  
  ci:
    uses: ./.github/workflows/ci.yml
  
  npm:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Publish to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  
  tag:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Tag a release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(jq -r '.version' package.json)
          hub release create -m $VERSION $VERSION
