name: Release

on:
  workflow_call:
  push:
   branches:
     workflow-fix

jobs:
  
  ci:
    uses: ./.github/workflows/ci.yml
  
  npm:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Login to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      
      - name: Publish to NPM
        run: npm publish
  
  tag:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Tag a release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(jq -r '.version' package.json)
          hub release create -m $VERSION $VERSION
