name: Tag release

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - name: Clone repository
      uses: actions/checkout@v3
      
    - name: Tag release
      uses: halvardssm/github-action-tag-release@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "./package.json"
