name: Update artifacts

on:
  push:
    branches:
      - main
    paths:
      - 'es-codec.ts'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install TypeScript
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[ci] build"
          git push
